Repository go-kratos/kratos, pull requests merged in 2022-07, with the labels that each got.

#2181 feat(http): add http router walk
  .github/workflows/go.yml
  transport/grpc/server.go
  transport/grpc/server_test.go
  transport/http/router.go
  transport/http/server.go
  transport/http/server_test.go
Labels: feature

#2235 fix: zookeeper add auto re-register
  contrib/registry/zookeeper/register.go
Labels: bug

#2207 feat: support passing program args with run cmd
  cmd/kratos/internal/run/run.go
Labels: enhancement

#2200 proto build client structName not match to server's structName
  cmd/kratos/internal/proto/server/server.go
  cmd/kratos/internal/proto/server/server_test.go
Labels: bug

#2187 fix(grpc/codec): fix default behavior for gRPC encoding
  transport/grpc/codec.go
Labels: enhancement

#2239 feat(middleware): add selector matcher
  internal/matcher/middleware.go
  internal/matcher/middleware_test.go
  transport/grpc/interceptor.go
  transport/grpc/server.go
  transport/grpc/server_test.go
  transport/http/context.go
  transport/http/server.go
  transport/http/server_test.go
Labels: feature
