Repository go-kratos/kratos, pull requests merged in 2023-12, with the labels that each got.

#3097 fix: `sctx` cause request ctx canceled during graceful shutdown
  app.go
Labels: LGTM, size:XS

#3106 feat(config): config support custom merge config
  config/config.go
  config/config_test.go
  config/options.go
  config/options_test.go
  config/reader.go
  config/reader_test.go
Labels: LGTM, size:M

#3085 deps：update jwt v4 ->v5
  go.mod
  go.sum
  middleware/auth/jwt/jwt.go
  middleware/auth/jwt/jwt_test.go
Labels: LGTM, size:S

#3112 chore: upgrade github.com/gorilla/mux
  contrib/polaris/go.mod
  contrib/polaris/go.sum
  go.mod
  go.sum
Labels: LGTM, size:XS

#2985 fix(sec): upgrade github.com/buger/jsonparser to 1.1.1
  contrib/registry/nacos/go.mod
Labels: LGTM, size:XS

#3113 chore:chore update
  app.go
  contrib/config/consul/config.go
  contrib/registry/eureka/eureka.go
  contrib/registry/eureka/register.go
  contrib/registry/polaris/registry.go
  selector/filter/version.go
  transport/grpc/client.go
  transport/grpc/resolver/direct/builder.go
  transport/grpc/resolver/discovery/builder_test.go
  transport/http/client.go
  transport/http/resolver.go
  transport/http/server.go
Labels: LGTM, size:M

#3118 feat: support consul sign config change
  contrib/config/consul/watcher.go
Labels: LGTM, size:M

#2885 fix(encoding/form): time with the location set to local time
  encoding/form/well_known_types.go
  encoding/form/well_known_types_test.go
Labels: LGTM, size:XS

#3015 feat: improve node alg
  selector/node/ewma/node.go
  selector/node/ewma/node_test.go
Labels: LGTM, size:L
