Repository go-kratos/kratos, pull requests merged in 2024-06, with the labels that each got.

#3328 faat(encoding/form): allow change the default encoder and decoder tag name
  encoding/form/form.go
  encoding/form/form_test.go
Labels: LGTM, size:M

#3327 The issue that the response header is not assigned a value is fixed
  transport/http/client.go
Labels: LGTM, size:XS

#3306 feat: parsing config input and convert to match the type
  config/options.go
  config/options_test.go
Labels: LGTM, size:L

#3353 adds Set-Cookie method to the HTTP transport.
  transport/http/server.go
  transport/http/transport.go
Labels: LGTM, size:S
