Repository go-kratos/kratos, pull requests merged in 2024-08, with the labels that each got.

#3395 (fix): fixed typo
  api/metadata/server.go
Labels: LGTM, size:XS

#3392 feat(resolver/discovery): expose create watcher timeout error
  transport/grpc/resolver/discovery/builder.go
Labels: LGTM, size:XS

#3386 fix(registry/polaris): fix concurrent map iteration and map write #3361
  contrib/polaris/registry.go
  contrib/polaris/registry_test.go
Labels: LGTM, size:M

#3363 perf: optimize the http.ContentType method
  internal/httputil/http.go
Labels: LGTM, size:XS

#3364 chore: replace the DisableDebugLog method with the PrintDebugLog method
  transport/grpc/resolver/discovery/builder_test.go
Labels: LGTM, size:XS

#3403 add buf config for protoc-gen-go-errors
  cmd/protoc-gen-go-errors/buf.gen.yaml
  cmd/protoc-gen-go-errors/buf.lock
  cmd/protoc-gen-go-errors/buf.yaml
Labels: LGTM, size:S
