Repository go-kratos/kratos, pull requests merged in 2024-04, with the labels that each got.

#3284 [bugfix] compatile both map[kratos] and map.kratos for a map type in the quer…
  encoding/form/proto_decode.go
Labels: LGTM, size:S

#3264 security: upgrade google.golang.org/protobuf to 1.33.0
  contrib/config/apollo/go.mod
  contrib/config/apollo/go.sum
  contrib/config/consul/go.mod
  contrib/config/consul/go.sum
  contrib/config/etcd/go.mod
  contrib/config/etcd/go.sum
  contrib/config/kubernetes/go.mod
  contrib/config/kubernetes/go.sum
  contrib/config/nacos/go.mod
  contrib/config/nacos/go.sum
  contrib/config/polaris/go.mod
  contrib/config/polaris/go.sum
  contrib/errortracker/sentry/go.mod
  contrib/errortracker/sentry/go.sum
  contrib/log/aliyun/go.mod
  contrib/log/aliyun/go.sum
  contrib/log/tencent/go.mod
  contrib/log/tencent/go.sum
  contrib/opensergo/go.mod
  contrib/opensergo/go.sum
  contrib/polaris/go.mod
  contrib/polaris/go.sum
  contrib/registry/etcd/go.mod
  contrib/registry/etcd/go.sum
  contrib/registry/kubernetes/go.mod
  contrib/registry/kubernetes/go.sum
  contrib/registry/polaris/go.mod
  contrib/registry/polaris/go.sum
  go.mod
  go.sum
Labels: LGTM, size:M

#3297 dep: change library name of mergo #3149
  config/config.go
  config/config_test.go
  config/reader_test.go
  contrib/config/apollo/go.mod
  contrib/config/apollo/go.sum
  contrib/config/consul/go.mod
  contrib/config/consul/go.sum
  contrib/config/etcd/go.mod
  contrib/config/etcd/go.sum
  contrib/config/kubernetes/go.mod
  contrib/config/kubernetes/go.sum
  contrib/config/nacos/go.mod
  contrib/config/nacos/go.sum
  contrib/config/polaris/go.mod
  contrib/config/polaris/go.sum
  contrib/polaris/go.mod
  contrib/polaris/go.sum
  contrib/registry/kubernetes/go.mod
  contrib/registry/kubernetes/go.sum
  go.mod
  go.sum
Labels: LGTM, size:S

#3300 fix(contrib/polaris): incorrect conversion between integer types
  contrib/polaris/router.go
Labels: LGTM, size:XS

#3298 chore(middleware/metrics): if requests and seconds are nil, return directory
  middleware/metrics/metrics.go
Labels: LGTM, size:XS

#3309 fix(contrib/opensergo): incorrect conversion between integer types
  contrib/opensergo/opensergo.go
  contrib/polaris/router.go
Labels: LGTM, size:XS
