Repository go-kratos/kratos, pull requests merged in 2024-01, with the labels that each got.

#3147 fix: fix consul heartbeat 404 error
  contrib/registry/consul/client.go
Labels: LGTM, size:XS

#3131 feat: add server option for NotFoundHandler and MethodNotAllowedHandler
  transport/http/server.go
  transport/http/server_test.go
Labels: LGTM, size:M

#3146 fix: clear err after app stop err handling
  app.go
Labels: LGTM, size:XS

#3122 feat(middleware): adding sentry as errortracker
  contrib/errortracker/sentry/README.md
  contrib/errortracker/sentry/go.mod
  contrib/errortracker/sentry/go.sum
  contrib/errortracker/sentry/sentry.go
  contrib/errortracker/sentry/sentry_test.go
Labels: LGTM, size:L
