Repository go-kratos/kratos, pull requests merged in 2024-07, with the labels that each got.

#3367 chroe: chore update
  contrib/config/polaris/config.go
  contrib/errortracker/sentry/sentry.go
  contrib/registry/discovery/discovery.go
  contrib/registry/zookeeper/register.go
Labels: LGTM, size:S

#3378 deps: upgrade kratos version to v2.8.0
  cmd/kratos/version.go
  cmd/protoc-gen-go-errors/version.go
  cmd/protoc-gen-go-http/version.go
  contrib/config/apollo/go.mod
  contrib/config/consul/go.mod
  contrib/config/etcd/go.mod
  contrib/config/kubernetes/go.mod
  contrib/config/nacos/go.mod
  contrib/config/polaris/go.mod
  contrib/encoding/msgpack/go.mod
  contrib/log/aliyun/go.mod
  contrib/log/fluent/go.mod
  contrib/log/logrus/go.mod
  contrib/log/tencent/go.mod
  contrib/log/zap/go.mod
  contrib/log/zerolog/go.mod
  contrib/opensergo/go.mod
  contrib/polaris/go.mod
  contrib/registry/consul/go.mod
  contrib/registry/discovery/go.mod
  contrib/registry/etcd/go.mod
  contrib/registry/eureka/go.mod
  contrib/registry/kubernetes/go.mod
  contrib/registry/nacos/go.mod
  contrib/registry/polaris/go.mod
  contrib/registry/zookeeper/go.mod
  version.go
Labels: LGTM, size:M

#3373 fix: filter redundant endpoints invalid
  transport/grpc/resolver/discovery/resolver.go
Labels: LGTM, size:XS
