Repository go-kratos/kratos, pull requests merged in 2024-02, with the labels that each got.

#3183 fix: test failed on other timezone.(#3181)
  encoding/form/form_test.go
  encoding/form/proto_encode_test.go
Labels: LGTM, size:S

#3171 fix: zap log print out multiple `msg`
  contrib/log/zap/zap.go
  contrib/log/zap/zap_test.go
Labels: LGTM, size:M

#3188 fix(protoc-gen-go-http): return nil if err == nil。
  cmd/protoc-gen-go-http/httpTemplate.tpl
Labels: LGTM, size:XS
