Repository go-kratos/kratos, pull requests merged in 2024-09, with the labels that each got.

#3357 feat(contrib/log/zap): If disable this level of logging entirely, av…
  contrib/log/zap/zap.go
Labels: LGTM, size:XS

#2770 test: remove non-existent test methods
  transport/http/client_test.go
  transport/http/server_test.go
Labels: LGTM, size:S

#3359 adding stream interceptor for logging middleware
  transport/grpc/client.go
  transport/grpc/interceptor.go
  transport/grpc/server.go
  transport/grpc/server_test.go
Labels: LGTM, size:L
