Repository go-kratos/kratos, pull requests merged in 2024-03, with the labels that each got.

#3218 fix(transport/http): no need to call EncodeURL twice in test
  transport/http/binding/encode_test.go
Labels: LGTM, size:XS

#3196 fix: use .MapKey to get key's FieldDescriptor
  encoding/form/proto_encode.go
Labels: LGTM, size:XS

#3236 build(go): Added support for go1.22.x
  .github/workflows/go.yml
Labels: LGTM, size:XS

#3235 build(lint): upgrade `golangci/golangci-lint-action`
  .github/workflows/lint.yml
Labels: LGTM, size:XS

#3221 feat(log): Prevent log.Helper sprintf from running early #3209
  log/helper.go
  log/helper_test.go
Labels: LGTM, size:M

#3187 fix: remove duplicate test codes.
  transport/http/binding/encode_test.go
Labels: LGTM, size:S

#3160 fix: polaris registry bug: nodes is empty at startup
  contrib/registry/polaris/registry.go
Labels: LGTM, size:XS

#3134 fix: logging middleware caller issue #3133
  middleware/logging/logging.go
  middleware/logging/logging_test.go
Labels: LGTM, size:M

#3121 feat: use writer directly in stdLogger.
  log/std.go
  log/std_test.go
Labels: LGTM, size:M

#3180 fix: etcd registry lifecycle
  contrib/registry/etcd/registry.go
Labels: LGTM, size:S

#3173 fix: nacos stop cannot cancel subscription
  contrib/registry/nacos/watcher.go
Labels: LGTM, size:S

#3162 fix(consul): unable to recreate after canceled the consul watch
  contrib/registry/consul/registry.go
  contrib/registry/consul/registry_test.go
  contrib/registry/consul/service.go
  contrib/registry/consul/watcher.go
Labels: LGTM, size:L

#3265 feat(transport/http): add unwrap method for returning underlying response writer
  transport/http/context.go
  transport/http/context_test.go
Labels: LGTM, size:S

#3234 fix(encoding/form): optimize EncodeField and add test cases
  encoding/form/proto_encode.go
  encoding/form/proto_encode_test.go
  internal/testdata/complex/complex.pb.go
  internal/testdata/complex/complex.proto
  internal/testdata/complex/generate.go
Labels: LGTM, size:L

#3257 fix(encoding/form): `Timestamp` use local time and fix test wrong mock time zone
  encoding/form/form_test.go
  encoding/form/proto_decode.go
  encoding/form/proto_encode_test.go
Labels: LGTM, size:S

#3266 deps: upgrade kratos version to v2.7.3
  cmd/kratos/version.go
  cmd/protoc-gen-go-errors/version.go
  cmd/protoc-gen-go-http/version.go
  contrib/config/apollo/go.mod
  contrib/config/consul/go.mod
  contrib/config/etcd/go.mod
  contrib/config/kubernetes/go.mod
  contrib/config/nacos/go.mod
  contrib/config/polaris/go.mod
  contrib/encoding/msgpack/go.mod
  contrib/log/aliyun/go.mod
  contrib/log/fluent/go.mod
  contrib/log/logrus/go.mod
  contrib/log/tencent/go.mod
  contrib/log/zap/go.mod
  contrib/log/zerolog/go.mod
  contrib/metrics/datadog/go.mod
  contrib/metrics/prometheus/go.mod
  contrib/opensergo/go.mod
  contrib/polaris/go.mod
  contrib/registry/consul/go.mod
  contrib/registry/discovery/go.mod
  contrib/registry/etcd/go.mod
  contrib/registry/eureka/go.mod
  contrib/registry/kubernetes/go.mod
  contrib/registry/nacos/go.mod
  contrib/registry/polaris/go.mod
  contrib/registry/zookeeper/go.mod
  version.go
Labels: LGTM, size:M
