Repository go-kratos/kratos, pull requests merged in 2024-10, with the labels that each got.

#3414 chore: upgrade golangci-lint version to v1.60.3 and fix lint
  .github/workflows/lint.yml
  .golangci.yml
  app.go
  cmd/kratos/internal/proto/client/client.go
  cmd/kratos/internal/run/run.go
  config/config_test.go
  config/env/env.go
  config/options.go
  config/options_test.go
  contrib/config/nacos/config_test.go
  contrib/opensergo/opensergo_test.go
  contrib/polaris/router.go
  contrib/registry/consul/registry_test.go
  contrib/registry/etcd/registry.go
  contrib/registry/eureka/client.go
  contrib/registry/kubernetes/registry.go
  contrib/registry/kubernetes/registry_test.go
  contrib/registry/nacos/registry_test.go
  contrib/registry/nacos/watcher.go
  contrib/registry/zookeeper/register_test.go
  encoding/encoding_test.go
  encoding/form/proto_decode.go
  errors/errors.go
  errors/types.go
  internal/host/host.go
  internal/matcher/middleware_test.go
  log/filter_test.go
  log/value_test.go
  metadata/metadata_test.go
  middleware/auth/jwt/jwt_test.go
  middleware/circuitbreaker/circuitbreaker_test.go
  middleware/logging/logging_test.go
  middleware/metrics/metrics.go
  middleware/metrics/metrics_test.go
  middleware/middleware_test.go
  middleware/ratelimit/ratelimit_test.go
  middleware/recovery/recovery.go
  middleware/recovery/recovery_test.go
  middleware/selector/selector_test.go
  middleware/tracing/span.go
  middleware/tracing/tracing_test.go
  middleware/validate/validate_test.go
  options_test.go
  selector/node/direct/direct.go
  selector/node/ewma/node.go
  selector/selector_test.go
  transport/grpc/client.go
  transport/grpc/client_test.go
  transport/grpc/server.go
  transport/grpc/server_test.go
  transport/http/binding/encode.go
  transport/http/client.go
  transport/http/client_test.go
  transport/http/context_test.go
  transport/http/router_test.go
  transport/http/server.go
  transport/http/server_test.go
Labels: LGTM, size:L

#3402 fix: when entering idle mode, the old resolve-related resources have …
  contrib/registry/consul/registry.go
  contrib/registry/consul/registry_test.go
  contrib/registry/consul/service.go
  contrib/registry/consul/watcher.go
Labels: LGTM, size:L

#3385 feat(middleware/metrics): make middleware histograms simply
  middleware/metrics/metrics.go
Labels: LGTM, size:XS

#3365 fix: add timeout configuration in grpc dial function
  transport/grpc/client.go
Labels: LGTM, size:XS

#3436 deps: upgrade kratos version to v2.8.1
  cmd/kratos/version.go
  cmd/protoc-gen-go-errors/version.go
  cmd/protoc-gen-go-http/version.go
  contrib/config/apollo/go.mod
  contrib/config/consul/go.mod
  contrib/config/etcd/go.mod
  contrib/config/kubernetes/go.mod
  contrib/config/nacos/go.mod
  contrib/config/polaris/go.mod
  contrib/encoding/msgpack/go.mod
  contrib/errortracker/sentry/go.mod
  contrib/log/aliyun/go.mod
  contrib/log/fluent/go.mod
  contrib/log/logrus/go.mod
  contrib/log/tencent/go.mod
  contrib/log/zap/go.mod
  contrib/log/zerolog/go.mod
  contrib/opensergo/go.mod
  contrib/polaris/go.mod
  contrib/registry/consul/go.mod
  contrib/registry/discovery/go.mod
  contrib/registry/etcd/go.mod
  contrib/registry/eureka/go.mod
  contrib/registry/kubernetes/go.mod
  contrib/registry/nacos/go.mod
  contrib/registry/polaris/go.mod
  contrib/registry/servicecomb/go.mod
  contrib/registry/servicecomb/go.sum
  contrib/registry/zookeeper/go.mod
  version.go
Labels: LGTM, size:M

#3447 fix: resolve the issue of metrics and logging code default to zero
  middleware/logging/logging.go
  middleware/metrics/metrics.go
Labels: LGTM, size:S

#3448 feat: create build Group in changelog generate.
  cmd/kratos/internal/change/get.go
Labels: LGTM, size:XS

#3449 fix: unit test Recycle watch resolver tick goroutine
  .github/workflows/go.yml
  contrib/registry/consul/registry_test.go
Labels: LGTM, size:M

#3452 deps: upgrade kratos version to v2.8.2
  cmd/kratos/version.go
  cmd/protoc-gen-go-errors/version.go
  cmd/protoc-gen-go-http/version.go
  contrib/config/apollo/go.mod
  contrib/config/consul/go.mod
  contrib/config/etcd/go.mod
  contrib/config/kubernetes/go.mod
  contrib/config/nacos/go.mod
  contrib/config/polaris/go.mod
  contrib/encoding/msgpack/go.mod
  contrib/errortracker/sentry/go.mod
  contrib/log/aliyun/go.mod
  contrib/log/fluent/go.mod
  contrib/log/logrus/go.mod
  contrib/log/tencent/go.mod
  contrib/log/zap/go.mod
  contrib/log/zerolog/go.mod
  contrib/opensergo/go.mod
  contrib/polaris/go.mod
  contrib/registry/consul/go.mod
  contrib/registry/discovery/go.mod
  contrib/registry/etcd/go.mod
  contrib/registry/eureka/go.mod
  contrib/registry/kubernetes/go.mod
  contrib/registry/nacos/go.mod
  contrib/registry/polaris/go.mod
  contrib/registry/servicecomb/go.mod
  contrib/registry/zookeeper/go.mod
  version.go
Labels: LGTM, size:M

#3454 fix: various typos
  .github/pull_request_template.md
  .golangci.yml
  README.md
  ROADMAP.md
  cmd/kratos/internal/proto/server/server.go
  config/options_test.go
  contrib/config/apollo/README.md
  contrib/config/kubernetes/README.md
  contrib/log/aliyun/aliyun.go
  contrib/registry/kubernetes/registry_test.go
  encoding/form/form_test.go
  encoding/form/proto_decode.go
  internal/matcher/middleware.go
  log/README.md
  log/filter_test.go
  middleware/tracing/metadata.go
  third_party/validate/validate.proto
  transport/grpc/resolver/discovery/builder.go
  transport/grpc/resolver/discovery/resolver.go
  transport/http/resolver.go
Labels: LGTM, size:M

#3455 fix: return inner Logger from GetLogger for log.WithContext reuse
  log/global.go
  log/global_test.go
Labels: bug, LGTM, size:S
