Repository go-kratos/kratos, pull requests merged in 2025-04, with the labels that each got.

#3603 docs: translate Chinese comments to English
  contrib/config/kubernetes/watcher.go
  contrib/registry/servicecomb/registry.go
  contrib/registry/servicecomb/watcher.go
  contrib/registry/zookeeper/watcher.go
Labels: LGTM, size:S

#3622 bc(contrib/log/aliyun): aliyun sls logger
  contrib/log/aliyun/aliyun.go
  contrib/log/aliyun/aliyun_test.go
  contrib/log/aliyun/go.mod
  contrib/log/aliyun/go.sum
Labels: LGTM, size:M

#3624 feat(transport): add Response method to Transport HTTP
  middleware/tracing/tracing_test.go
  transport/http/transport.go
  transport/http/transport_test.go
Labels: LGTM, size:S

#3625 docs: optimize readme zh docs
  README_zh.md
Labels: LGTM, size:M

#3642 deps:deps CVE-2025-30204 about golang-jwt
  go.mod
  go.sum
Labels: LGTM, size:XS

#3610 perf(config/file): optimize file format func
  config/file/format.go
Labels: LGTM, size:XS

#3602 refactor: extract key for reuse and maintainability
  contrib/registry/etcd/registry.go
Labels: LGTM, size:S

#3592 perf(encoding/form): optimize camelCase and snakeCase conversion
  encoding/form/proto_decode.go
  encoding/form/proto_encode.go
Labels: LGTM, size:S

#3643 github: Remove submodule dependencies in Dependabot.
  .github/dependabot.yml
  .github/workflows/go.yml
  .github/workflows/lint.yml
  .golangci.yml
  cmd/kratos/internal/base/path.go
  contrib/polaris/router.go
  contrib/registry/discovery/impl_discover.go
  encoding/form/form_test.go
  internal/group/group.go
  internal/group/group_test.go
  middleware/circuitbreaker/circuitbreaker.go
  middleware/circuitbreaker/circuitbreaker_test.go
  transport/grpc/server.go
  transport/http/server.go
Labels: LGTM, size:L

#3646 mcp: Add MCP Transport
  contrib/transport/mcp/README.md
  contrib/transport/mcp/go.mod
  contrib/transport/mcp/go.sum
  contrib/transport/mcp/server.go
  contrib/transport/mcp/server_test.go
Labels: LGTM, size:L

#3648 go mod tidy
  cmd/protoc-gen-go-errors/go.sum
  contrib/config/apollo/go.mod
  contrib/config/apollo/go.sum
  contrib/config/consul/go.mod
  contrib/config/consul/go.sum
  contrib/config/etcd/go.mod
  contrib/config/etcd/go.sum
  contrib/config/kubernetes/go.mod
  contrib/config/kubernetes/go.sum
  contrib/config/nacos/go.sum
  contrib/config/polaris/go.mod
  contrib/config/polaris/go.sum
  contrib/encoding/msgpack/go.sum
  contrib/errortracker/sentry/go.mod
  contrib/errortracker/sentry/go.sum
  contrib/log/aliyun/go.mod
  contrib/log/aliyun/go.sum
  contrib/log/fluent/go.sum
  contrib/log/logrus/go.mod
  contrib/log/logrus/go.sum
  contrib/log/tencent/go.sum
  contrib/log/zap/go.sum
  contrib/log/zerolog/go.mod
  contrib/log/zerolog/go.sum
  contrib/opensergo/go.mod
  contrib/opensergo/go.sum
  contrib/polaris/go.mod
  contrib/polaris/go.sum
  contrib/registry/consul/go.mod
  contrib/registry/consul/go.sum
  contrib/registry/discovery/go.mod
  contrib/registry/discovery/go.sum
  contrib/registry/etcd/go.mod
  contrib/registry/etcd/go.sum
  contrib/registry/kubernetes/go.mod
  contrib/registry/kubernetes/go.sum
  contrib/registry/nacos/go.sum
  contrib/registry/polaris/go.mod
  contrib/registry/polaris/go.sum
  contrib/registry/servicecomb/go.mod
  contrib/registry/servicecomb/go.sum
  contrib/registry/zookeeper/go.mod
  contrib/registry/zookeeper/go.sum
  contrib/transport/mcp/go.sum
Labels: LGTM, size:M

#3594 refactor(contrib/registry/etcd): use Namespace Name and ID as the unique keys
  contrib/registry/etcd/registry.go
Labels: LGTM, size:XS

#3649 add mcp middleware
  contrib/transport/mcp/README.md
  contrib/transport/mcp/server.go
Labels: LGTM, size:M

#3645 perf(config/env): use strings.Cut to optimize env load method
  config/env/env.go
Labels: LGTM, size:S

#3517 fix: Fixed zookeeper watcher exiting the loop under exceptional condi…
  contrib/registry/zookeeper/watcher.go
Labels: LGTM, size:XS

#3421 fix(internal/host): Extract optimizes the return of the minimum index IP
  internal/host/host.go
Labels: LGTM, size:S

#3651 Revert "refactor: replace repeated error reasons with constants"
  contrib/middleware/validate/validate.go
  contrib/polaris/ratelimit.go
  errors/errors.go
  middleware/ratelimit/ratelimit.go
  middleware/validate/validate.go
  transport/http/binding/bind.go
  transport/http/binding/bind_test.go
  transport/http/codec.go
Labels: LGTM, size:M
