Repository go-kratos/kratos, pull requests merged in 2025-03, with the labels that each got.

#3550 feat: disable grpc reflection configuration
  transport/grpc/server.go
Labels: LGTM, size:M

#3558 deps: upgrade kratos version to v2.8.4
  cmd/kratos/version.go
  cmd/protoc-gen-go-errors/version.go
  cmd/protoc-gen-go-http/version.go
  contrib/config/apollo/go.mod
  contrib/config/consul/go.mod
  contrib/config/etcd/go.mod
  contrib/config/kubernetes/go.mod
  contrib/config/nacos/go.mod
  contrib/config/polaris/go.mod
  contrib/encoding/msgpack/go.mod
  contrib/errortracker/sentry/go.mod
  contrib/log/aliyun/go.mod
  contrib/log/fluent/go.mod
  contrib/log/logrus/go.mod
  contrib/log/tencent/go.mod
  contrib/log/zap/go.mod
  contrib/log/zerolog/go.mod
  contrib/middleware/validate/go.mod
  contrib/middleware/validate/go.sum
  contrib/opensergo/go.mod
  contrib/polaris/go.mod
  contrib/registry/consul/go.mod
  contrib/registry/discovery/go.mod
  contrib/registry/etcd/go.mod
  contrib/registry/eureka/go.mod
  contrib/registry/kubernetes/go.mod
  contrib/registry/nacos/go.mod
  contrib/registry/polaris/go.mod
  contrib/registry/servicecomb/go.mod
  contrib/registry/zookeeper/go.mod
  version.go
Labels: LGTM, size:M

#3506 perf(contrib/config/etcd): optimize Next method of etcd watcher
  contrib/config/etcd/watcher.go
Labels: LGTM, size:XS

#3561 feat(registry/nacos): support service discovery weight
  contrib/registry/nacos/registry.go
  contrib/registry/nacos/registry_test.go
Labels: LGTM, size:M

#3474 perf(contrib/polaris): optimize Load method by preallocating slice capacity
  contrib/polaris/config.go
Labels: LGTM, size:XS

#3509 refactor(contrib/registry/etcd): use service ID as Registry.ctxMap key instead of service pointer
  contrib/registry/etcd/registry.go
Labels: LGTM, size:S

#3475 perf(config): refactor atomicValue Bool method by optimizing string handling
  config/value.go
Labels: LGTM, size:XS

#3572 deps(contrib/middleware/validate): update protovalidate-go to v0.9.2
  contrib/middleware/validate/go.mod
  contrib/middleware/validate/go.sum
  contrib/middleware/validate/internal/testdata/generate.go
  contrib/middleware/validate/internal/testdata/test.pb.go
  contrib/middleware/validate/internal/testdata/test.pb.validate.go
  contrib/middleware/validate/validate.go
Labels: LGTM, size:L
